import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Bus booking App',
  description: 'Generated by Nurislam Mridha',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script type="text/javascript" src="../static/script.js" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
